name: Style Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Docker Lint
        run: docker build -t goxy-lint -f Dockerfile-lint .

      - name: Run Docker Lint
        run: docker run -i goxy-lint sh -c "cd  /go/src/github.com/bshramin/goxy && golangci-lint run"
