name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Docker Test
        run: docker build -t goxy-test -f Dockerfile-test .

      - name: Run Docker Test
        run: docker run -i goxy-test sh -c "cd /go/src/github.com/bshramin/goxy && go test -v -mod=vendor ./..."
